"""empty message

Revision ID: 10555f99d464
Revises: 556d683d37a8
Create Date: 2020-02-26 23:40:42.082234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10555f99d464'
down_revision = '556d683d37a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['subscription.subscription_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_details')
    # ### end Alembic commands ###
