"""empty message

Revision ID: 556d683d37a8
Revises: ad563a3d83e9
Create Date: 2020-02-09 01:06:28.055229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556d683d37a8'
down_revision = 'ad563a3d83e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'subscription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###
