"""empty message

Revision ID: 0ccd82f44ee3
Revises: a0ee30c8697e
Create Date: 2020-02-03 16:36:27.506087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccd82f44ee3'
down_revision = 'a0ee30c8697e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apod', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apod', sa.Column('id', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
