"""empty message

Revision ID: 116d3ce73c86
Revises: 
Create Date: 2020-02-03 19:27:56.485356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116d3ce73c86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apod', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apod', sa.Column('id', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
